appIngresoEgreso/Controllers/FamiliaController.cs
using appIngresoEgreso.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace appIngresoEgreso.Controllers
{
    [Authorize]
    public class FamiliaController : Controller
    {
        private readonly IMiembroService _familiaService;
        public FamiliaController(IMiembroService familiaService)
        {
            _familiaService = familiaService;
        }
        public IActionResult Index()
        {
            return View(_familiaService.GetFamiliaInfoList());
        }
    }
}

appIngresoEgreso/Controllers/GastoController.cs
using appIngresoEgreso.Enums;
using appIngresoEgreso.Models.ViewModels;
using appIngresoEgreso.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace appIngresoEgreso.Controllers
{
    [Authorize]
    public class GastoController : Controller
    {
        private readonly IMiembroService _miembroService;
        private readonly IGastoService _gastoService;
        private readonly ICategoriaService _categoriaService;
        public GastoController(
            IMiembroService miembroService,
            IGastoService gastoService,
            ICategoriaService categoriaService)
        {
            _miembroService = miembroService;
            _gastoService = gastoService;
            _categoriaService = categoriaService;
        }
        public IActionResult Index() => View();
        public IActionResult Registrar()
        {
            MiembrosSelectList();
            MetodosPagoSelectList();
            CategoriasSelectLis();
            return View(new AgregarGastoViewModel());
        }
        [HttpPost]
        public IActionResult Registrar(AgregarGastoViewModel viewModel) 
        {
            if (!ModelState.IsValid)
            {
                MiembrosSelectList();
                MetodosPagoSelectList();
                CategoriasSelectLis();
                ModelState.AddModelError(string.Empty, "No se puedo registrar el gasto");
                return View(viewModel);
            }
            bool result = _gastoService.Registrar(viewModel);
            if (!result)
            {
                MiembrosSelectList();
                MetodosPagoSelectList();
                CategoriasSelectLis();
                ModelState.AddModelError(string.Empty, "No se puedo registrar el gasto");
                return View(viewModel);
            }
            return RedirectToAction("Index");
        }
        private void CategoriasSelectLis()
        {
            var list = _categoriaService.CategoriasSelect();
            ViewBag.Categorias = new SelectList(list,"IdCategoria","Nombre");
        }
        private void MiembrosSelectList()
        {
            var listMiembros = _miembroService.SelectList();
            ViewBag.Miembros = new SelectList(listMiembros, "IdMiembro", "Nombre");
        }
        private void MetodosPagoSelectList() {
            ViewBag.MetodosPago = new SelectList(
                Enum.GetValues(typeof(MetodoPago))
                .Cast<MetodoPago>().ToList());
        }
    }
}

appIngresoEgreso/Controllers/IngresoController.cs
using appIngresoEgreso.Models.ViewModels;
using appIngresoEgreso.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace appIngresoEgreso.Controllers
{
    [Authorize]
    public class IngresoController : Controller
    {
        private readonly IIngresoService _ingresoServiec;
        private readonly IMiembroService _miembroService;

        public IngresoController(
            IIngresoService ingresoServiec,
            IMiembroService miembroService)
        {
            _ingresoServiec = ingresoServiec;
            _miembroService = miembroService;
        }

        public IActionResult Agregar()
        {
            CargarMiembroSelectList();
            return View(new AgregarIngresoViewModel());
        }
        [HttpPost]
        public IActionResult Agregar(AgregarIngresoViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                CargarMiembroSelectList();
                return View(viewModel);
            }
            ViewBag.mensaje = _ingresoServiec.RegistrarIngreso(viewModel);
            CargarMiembroSelectList();
            return View();
        }
        private void CargarMiembroSelectList()
        {
            var list = _miembroService.SelectList();
            ViewBag.miembros = new SelectList(list, "IdMiembro", "Nombre");
        }
    }
}

appIngresoEgreso/Controllers/PagoController.cs
using appIngresoEgreso.Dao;
using appIngresoEgreso.Models.ViewModels;
using appIngresoEgreso.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace appIngresoEgreso.Controllers
{
    [Authorize]
    public class PagoController : Controller
    {
        private readonly IPagoServicioService _pagoServicioService;
        private readonly IServicioService _servicioService;
        private readonly IMiembroService _miembroService;
        public PagoController(IPagoServicioService pagoServicioService, IServicioService servicioService, IMiembroService miembroService)
        {
            _pagoServicioService = pagoServicioService;
            _servicioService = servicioService;
            _miembroService = miembroService;
        }
        public IActionResult Pagar()
        {
            CargarServicioSelectList(); 
            PagarServicioViewModel viewModel = new PagarServicioViewModel();
            viewModel.FechaPago = DateTime.Now;
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult Pagar(PagarServicioViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                CargarServicioSelectList();
                return View(viewModel);
            }
            var result = _pagoServicioService.RealizarPagoServicio(viewModel);
            if(result.Item1)
            {
                TempData["Mensaje"] = result.Item2;
                return RedirectToAction("Index", "Dashboard");
            }
            ViewBag.mensaje = result.Item2;
            CargarServicioSelectList();
            return View(viewModel); 
        }
        private void CargarServicioSelectList()
        {
            var list = _servicioService.GetSelectListServicios();
            var miembroFamiliaList = _miembroService.SelectList();
            ViewBag.Servicios = new SelectList(list, "ServicioId", "Nombre");
            ViewBag.Miembros = new SelectList(miembroFamiliaList, "IdMiembro", "Nombre");
        }
    }
}

appIngresoEgreso/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - appIngresoEgreso</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/appIngresoEgreso.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Dashboard" asp-action="Index">Aplicación Gestión de Gastos/Servicios familiares</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gasto" asp-action="Registrar">Nuevo Gasto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Index">Categorias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ingreso" asp-action="Agregar">Ingreso</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Familia" asp-action="Index">Mi Familia</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pago" asp-action="Pagar">Pagar Servicio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - appIngresoEgreso - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>